"""tracking categories

Revision ID: 7e785c745bdc
Revises: 4c1d8e2a9f37
Create Date: 2026-10-09 00:15:02.025068
"""

import sqlalchemy as sa
from alembic import op

from migrations import policies

revision = '7e785c745bdc'
down_revision = '4c1d8e2a9f37'
branch_labels = None
depends_on = None

NEW_WORKSPACE_TABLES = (
    "group_tracking_categories", "group_tracking_options", "entity_tracking_categories",
    "entity_tracking_options", "tracking_category_mappings", "tracking_option_mappings",
)
ACCOUNT_OPERATIONS = "'create_account', 'update_account', 'archive_account'"
TRACKING_OPERATIONS = (
    "'create_tracking_category', 'create_tracking_option', 'update_tracking_category', "
    "'update_tracking_option', 'archive_tracking_category', 'archive_tracking_option'"
)


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('entity_tracking_categories',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('entity_id', sa.Uuid(), nullable=False),
    sa.Column('xero_category_id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('synced_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['entity_id'], ['entities.id'], name=op.f('fk_entity_tracking_categories_entity_id_entities'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_entity_tracking_categories_workspace_id_workspaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_entity_tracking_categories')),
    sa.UniqueConstraint('entity_id', 'xero_category_id', name=op.f('uq_entity_tracking_categories_entity_id_xero_category_id'))
    )
    op.create_index(op.f('ix_entity_tracking_categories_entity_id'), 'entity_tracking_categories', ['entity_id'], unique=False)
    op.create_index(op.f('ix_entity_tracking_categories_workspace_id'), 'entity_tracking_categories', ['workspace_id'], unique=False)
    op.create_table('group_tracking_categories',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('source_entity_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.CheckConstraint("status in ('active', 'archived')", name=op.f('ck_group_tracking_categories_status_valid')),
    sa.ForeignKeyConstraint(['source_entity_id'], ['entities.id'], name=op.f('fk_group_tracking_categories_source_entity_id_entities'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_group_tracking_categories_workspace_id_workspaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_group_tracking_categories')),
    sa.UniqueConstraint('workspace_id', 'name', name=op.f('uq_group_tracking_categories_workspace_id_name'))
    )
    op.create_index(op.f('ix_group_tracking_categories_workspace_id'), 'group_tracking_categories', ['workspace_id'], unique=False)
    op.create_table('entity_tracking_options',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('entity_id', sa.Uuid(), nullable=False),
    sa.Column('category_id', sa.Uuid(), nullable=False),
    sa.Column('xero_option_id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('synced_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['entity_tracking_categories.id'], name=op.f('fk_entity_tracking_options_category_id_entity_tracking_categories'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['entity_id'], ['entities.id'], name=op.f('fk_entity_tracking_options_entity_id_entities'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_entity_tracking_options_workspace_id_workspaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_entity_tracking_options')),
    sa.UniqueConstraint('entity_id', 'xero_option_id', name=op.f('uq_entity_tracking_options_entity_id_xero_option_id'))
    )
    op.create_index(op.f('ix_entity_tracking_options_category_id'), 'entity_tracking_options', ['category_id'], unique=False)
    op.create_index(op.f('ix_entity_tracking_options_entity_id'), 'entity_tracking_options', ['entity_id'], unique=False)
    op.create_index(op.f('ix_entity_tracking_options_workspace_id'), 'entity_tracking_options', ['workspace_id'], unique=False)
    op.create_table('group_tracking_options',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('category_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.CheckConstraint("status in ('active', 'archived')", name=op.f('ck_group_tracking_options_status_valid')),
    sa.ForeignKeyConstraint(['category_id'], ['group_tracking_categories.id'], name=op.f('fk_group_tracking_options_category_id_group_tracking_categories'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_group_tracking_options_workspace_id_workspaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_group_tracking_options')),
    sa.UniqueConstraint('category_id', 'name', name=op.f('uq_group_tracking_options_category_id_name'))
    )
    op.create_index(op.f('ix_group_tracking_options_category_id'), 'group_tracking_options', ['category_id'], unique=False)
    op.create_index(op.f('ix_group_tracking_options_workspace_id'), 'group_tracking_options', ['workspace_id'], unique=False)
    op.create_table('tracking_category_mappings',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('entity_id', sa.Uuid(), nullable=False),
    sa.Column('entity_category_id', sa.Uuid(), nullable=False),
    sa.Column('group_category_id', sa.Uuid(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('source', sa.String(length=16), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('reasoning', sa.Text(), nullable=False),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('decided_by', sa.Uuid(), nullable=True),
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.CheckConstraint("status in ('suggested', 'confirmed', 'rejected')", name=op.f('ck_tracking_category_mappings_status_valid')),
    sa.ForeignKeyConstraint(['decided_by'], ['users.id'], name=op.f('fk_tracking_category_mappings_decided_by_users')),
    sa.ForeignKeyConstraint(['entity_category_id'], ['entity_tracking_categories.id'], name=op.f('fk_tracking_category_mappings_entity_category_id_entity_tracking_categories'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['entity_id'], ['entities.id'], name=op.f('fk_tracking_category_mappings_entity_id_entities'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['group_category_id'], ['group_tracking_categories.id'], name=op.f('fk_tracking_category_mappings_group_category_id_group_tracking_categories'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_tracking_category_mappings_workspace_id_workspaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tracking_category_mappings')),
    sa.UniqueConstraint('entity_category_id', name=op.f('uq_tracking_category_mappings_entity_category_id'))
    )
    op.create_index(op.f('ix_tracking_category_mappings_entity_id'), 'tracking_category_mappings', ['entity_id'], unique=False)
    op.create_index(op.f('ix_tracking_category_mappings_group_category_id'), 'tracking_category_mappings', ['group_category_id'], unique=False)
    op.create_index(op.f('ix_tracking_category_mappings_workspace_id'), 'tracking_category_mappings', ['workspace_id'], unique=False)
    op.create_table('tracking_option_mappings',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('entity_id', sa.Uuid(), nullable=False),
    sa.Column('entity_option_id', sa.Uuid(), nullable=False),
    sa.Column('group_option_id', sa.Uuid(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('source', sa.String(length=16), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('reasoning', sa.Text(), nullable=False),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('decided_by', sa.Uuid(), nullable=True),
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.CheckConstraint("status in ('suggested', 'confirmed', 'rejected')", name=op.f('ck_tracking_option_mappings_status_valid')),
    sa.ForeignKeyConstraint(['decided_by'], ['users.id'], name=op.f('fk_tracking_option_mappings_decided_by_users')),
    sa.ForeignKeyConstraint(['entity_id'], ['entities.id'], name=op.f('fk_tracking_option_mappings_entity_id_entities'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['entity_option_id'], ['entity_tracking_options.id'], name=op.f('fk_tracking_option_mappings_entity_option_id_entity_tracking_options'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['group_option_id'], ['group_tracking_options.id'], name=op.f('fk_tracking_option_mappings_group_option_id_group_tracking_options'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_tracking_option_mappings_workspace_id_workspaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tracking_option_mappings')),
    sa.UniqueConstraint('entity_option_id', name=op.f('uq_tracking_option_mappings_entity_option_id'))
    )
    op.create_index(op.f('ix_tracking_option_mappings_entity_id'), 'tracking_option_mappings', ['entity_id'], unique=False)
    op.create_index(op.f('ix_tracking_option_mappings_group_option_id'), 'tracking_option_mappings', ['group_option_id'], unique=False)
    op.create_index(op.f('ix_tracking_option_mappings_workspace_id'), 'tracking_option_mappings', ['workspace_id'], unique=False)
    op.add_column('change_items', sa.Column('entity_tracking_category_id', sa.Uuid(), nullable=True))
    op.add_column('change_items', sa.Column('entity_tracking_option_id', sa.Uuid(), nullable=True))
    op.add_column('change_items', sa.Column('group_tracking_category_id', sa.Uuid(), nullable=True))
    op.add_column('change_items', sa.Column('group_tracking_option_id', sa.Uuid(), nullable=True))
    op.add_column('change_items', sa.Column('created_xero_id', sa.String(length=64), nullable=True))
    op.create_foreign_key(op.f('fk_change_items_entity_tracking_option_id_entity_tracking_options'), 'change_items', 'entity_tracking_options', ['entity_tracking_option_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('fk_change_items_group_tracking_option_id_group_tracking_options'), 'change_items', 'group_tracking_options', ['group_tracking_option_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('fk_change_items_group_tracking_category_id_group_tracking_categories'), 'change_items', 'group_tracking_categories', ['group_tracking_category_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('fk_change_items_entity_tracking_category_id_entity_tracking_categories'), 'change_items', 'entity_tracking_categories', ['entity_tracking_category_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###
    op.drop_constraint(op.f('ck_change_items_operation_valid'), 'change_items', type_='check')
    op.create_check_constraint(op.f('ck_change_items_operation_valid'), 'change_items',
                               f"operation in ({ACCOUNT_OPERATIONS}, {TRACKING_OPERATIONS})")
    op.execute(policies.workspace_isolation_sql(NEW_WORKSPACE_TABLES))


def downgrade() -> None:
    op.execute("DELETE FROM change_items WHERE operation LIKE '%tracking%'")
    op.drop_constraint(op.f('ck_change_items_operation_valid'), 'change_items', type_='check')
    op.create_check_constraint(op.f('ck_change_items_operation_valid'), 'change_items',
                               f"operation in ({ACCOUNT_OPERATIONS})")
    for table in NEW_WORKSPACE_TABLES:
        op.execute(f"DROP POLICY IF EXISTS workspace_isolation ON {table}")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_change_items_entity_tracking_category_id_entity_tracking_categories'), 'change_items', type_='foreignkey')
    op.drop_constraint(op.f('fk_change_items_group_tracking_category_id_group_tracking_categories'), 'change_items', type_='foreignkey')
    op.drop_constraint(op.f('fk_change_items_group_tracking_option_id_group_tracking_options'), 'change_items', type_='foreignkey')
    op.drop_constraint(op.f('fk_change_items_entity_tracking_option_id_entity_tracking_options'), 'change_items', type_='foreignkey')
    op.drop_column('change_items', 'created_xero_id')
    op.drop_column('change_items', 'group_tracking_option_id')
    op.drop_column('change_items', 'group_tracking_category_id')
    op.drop_column('change_items', 'entity_tracking_option_id')
    op.drop_column('change_items', 'entity_tracking_category_id')
    op.drop_index(op.f('ix_tracking_option_mappings_workspace_id'), table_name='tracking_option_mappings')
    op.drop_index(op.f('ix_tracking_option_mappings_group_option_id'), table_name='tracking_option_mappings')
    op.drop_index(op.f('ix_tracking_option_mappings_entity_id'), table_name='tracking_option_mappings')
    op.drop_table('tracking_option_mappings')
    op.drop_index(op.f('ix_tracking_category_mappings_workspace_id'), table_name='tracking_category_mappings')
    op.drop_index(op.f('ix_tracking_category_mappings_group_category_id'), table_name='tracking_category_mappings')
    op.drop_index(op.f('ix_tracking_category_mappings_entity_id'), table_name='tracking_category_mappings')
    op.drop_table('tracking_category_mappings')
    op.drop_index(op.f('ix_group_tracking_options_workspace_id'), table_name='group_tracking_options')
    op.drop_index(op.f('ix_group_tracking_options_category_id'), table_name='group_tracking_options')
    op.drop_table('group_tracking_options')
    op.drop_index(op.f('ix_entity_tracking_options_workspace_id'), table_name='entity_tracking_options')
    op.drop_index(op.f('ix_entity_tracking_options_entity_id'), table_name='entity_tracking_options')
    op.drop_index(op.f('ix_entity_tracking_options_category_id'), table_name='entity_tracking_options')
    op.drop_table('entity_tracking_options')
    op.drop_index(op.f('ix_group_tracking_categories_workspace_id'), table_name='group_tracking_categories')
    op.drop_table('group_tracking_categories')
    op.drop_index(op.f('ix_entity_tracking_categories_workspace_id'), table_name='entity_tracking_categories')
    op.drop_index(op.f('ix_entity_tracking_categories_entity_id'), table_name='entity_tracking_categories')
    op.drop_table('entity_tracking_categories')
    # ### end Alembic commands ###
