"""baseline schema

Revision ID: 19627eb25682
Revises: 
Create Date: 2026-09-24 01:12:06.536528
"""

import sqlalchemy as sa
from alembic import op
from procrastinate.schema import SchemaManager
from sqlalchemy.dialects import postgresql

from migrations import policies

revision = '19627eb25682'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('oauth_states',
    sa.Column('state', sa.String(length=64), nullable=False),
    sa.Column('purpose', sa.String(length=16), nullable=False),
    sa.Column('nonce', sa.String(length=64), nullable=False),
    sa.Column('code_verifier', sa.String(length=128), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('workspace_id', sa.Uuid(), nullable=True),
    sa.Column('redirect_to', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('state', name=op.f('pk_oauth_states'))
    )
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('xero_user_id', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('xero_user_id', name=op.f('uq_users_xero_user_id'))
    )
    op.create_table('xero_quota',
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('min_remaining', sa.Integer(), nullable=True),
    sa.Column('day_remaining', sa.Integer(), nullable=True),
    sa.Column('retry_after_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('tenant_id', name=op.f('pk_xero_quota'))
    )
    op.create_table('workspaces',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_workspaces_created_by_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_workspaces'))
    )
    op.create_table('audit_events',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('workspace_id', sa.Uuid(), nullable=True),
    sa.Column('actor_user_id', sa.Uuid(), nullable=True),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('target_type', sa.String(length=64), nullable=True),
    sa.Column('target_id', sa.String(length=64), nullable=True),
    sa.Column('before', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('after', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('request_id', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], name=op.f('fk_audit_events_actor_user_id_users')),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_audit_events_workspace_id_workspaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_events'))
    )
    op.create_index(op.f('ix_audit_events_workspace_id'), 'audit_events', ['workspace_id'], unique=False)
    op.create_table('invitations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('role', sa.Enum('owner', 'admin', 'preparer', 'approver', 'viewer', name='role'), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('invited_by', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('accepted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('accepted_by', sa.Uuid(), nullable=True),
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['accepted_by'], ['users.id'], name=op.f('fk_invitations_accepted_by_users')),
    sa.ForeignKeyConstraint(['invited_by'], ['users.id'], name=op.f('fk_invitations_invited_by_users')),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_invitations_workspace_id_workspaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_invitations')),
    sa.UniqueConstraint('token_hash', name=op.f('uq_invitations_token_hash'))
    )
    op.create_index(op.f('ix_invitations_workspace_id'), 'invitations', ['workspace_id'], unique=False)
    op.create_table('memberships',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('role', sa.Enum('owner', 'admin', 'preparer', 'approver', 'viewer', name='role'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_memberships_user_id_users'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_memberships_workspace_id_workspaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_memberships')),
    sa.UniqueConstraint('workspace_id', 'user_id', name=op.f('uq_memberships_workspace_id_user_id'))
    )
    op.create_index(op.f('ix_memberships_user_id'), 'memberships', ['user_id'], unique=False)
    op.create_index(op.f('ix_memberships_workspace_id'), 'memberships', ['workspace_id'], unique=False)
    op.create_table('sessions',
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('csrf_token', sa.String(length=64), nullable=False),
    sa.Column('active_workspace_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['active_workspace_id'], ['workspaces.id'], name=op.f('fk_sessions_active_workspace_id_workspaces'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_sessions_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('token_hash', name=op.f('pk_sessions'))
    )
    op.create_index(op.f('ix_sessions_user_id'), 'sessions', ['user_id'], unique=False)
    op.create_table('xero_connections',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('xero_user_id', sa.String(length=64), nullable=False),
    sa.Column('connected_by', sa.Uuid(), nullable=False),
    sa.Column('token_encrypted', sa.Text(), nullable=False),
    sa.Column('scopes', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('last_refreshed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['connected_by'], ['users.id'], name=op.f('fk_xero_connections_connected_by_users')),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_xero_connections_workspace_id_workspaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_xero_connections')),
    sa.UniqueConstraint('workspace_id', 'xero_user_id', name=op.f('uq_xero_connections_workspace_id_xero_user_id'))
    )
    op.create_index(op.f('ix_xero_connections_workspace_id'), 'xero_connections', ['workspace_id'], unique=False)
    op.create_table('entities',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('connection_id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('xero_connection_ref', sa.String(length=64), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('base_currency', sa.String(length=3), nullable=True),
    sa.Column('country_code', sa.String(length=2), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('sync_status', sa.String(length=16), nullable=False),
    sa.Column('sync_error', sa.Text(), nullable=True),
    sa.Column('last_synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('accounts_modified_since', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['connection_id'], ['xero_connections.id'], name=op.f('fk_entities_connection_id_xero_connections'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_entities_workspace_id_workspaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_entities')),
    sa.UniqueConstraint('workspace_id', 'tenant_id', name=op.f('uq_entities_workspace_id_tenant_id'))
    )
    op.create_index(op.f('ix_entities_connection_id'), 'entities', ['connection_id'], unique=False)
    op.create_index(op.f('ix_entities_workspace_id'), 'entities', ['workspace_id'], unique=False)
    op.create_table('entity_accounts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('entity_id', sa.Uuid(), nullable=False),
    sa.Column('xero_account_id', sa.String(length=64), nullable=False),
    sa.Column('code', sa.String(length=32), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('type', sa.String(length=32), nullable=False),
    sa.Column('account_class', sa.String(length=16), nullable=True),
    sa.Column('tax_type', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('system_account', sa.String(length=64), nullable=True),
    sa.Column('reporting_code', sa.String(length=64), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('xero_updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('synced_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['entity_id'], ['entities.id'], name=op.f('fk_entity_accounts_entity_id_entities'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_entity_accounts_workspace_id_workspaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_entity_accounts')),
    sa.UniqueConstraint('entity_id', 'xero_account_id', name=op.f('uq_entity_accounts_entity_id_xero_account_id'))
    )
    op.create_index(op.f('ix_entity_accounts_entity_id'), 'entity_accounts', ['entity_id'], unique=False)
    op.create_index(op.f('ix_entity_accounts_workspace_id'), 'entity_accounts', ['workspace_id'], unique=False)
    op.create_table('group_accounts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('type', sa.String(length=32), nullable=False),
    sa.Column('account_class', sa.String(length=16), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('source_entity_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['source_entity_id'], ['entities.id'], name=op.f('fk_group_accounts_source_entity_id_entities'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_group_accounts_workspace_id_workspaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_group_accounts')),
    sa.UniqueConstraint('workspace_id', 'code', name=op.f('uq_group_accounts_workspace_id_code'))
    )
    op.create_index(op.f('ix_group_accounts_workspace_id'), 'group_accounts', ['workspace_id'], unique=False)
    op.create_table('sync_runs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('entity_id', sa.Uuid(), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('records_seen', sa.Integer(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['entity_id'], ['entities.id'], name=op.f('fk_sync_runs_entity_id_entities'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_sync_runs_workspace_id_workspaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sync_runs'))
    )
    op.create_index(op.f('ix_sync_runs_entity_id'), 'sync_runs', ['entity_id'], unique=False)
    op.create_index(op.f('ix_sync_runs_workspace_id'), 'sync_runs', ['workspace_id'], unique=False)
    op.create_table('account_mappings',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('entity_id', sa.Uuid(), nullable=False),
    sa.Column('entity_account_id', sa.Uuid(), nullable=False),
    sa.Column('group_account_id', sa.Uuid(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('source', sa.String(length=16), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('reasoning', sa.Text(), nullable=False),
    sa.Column('decided_by', sa.Uuid(), nullable=True),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.CheckConstraint("status in ('suggested','confirmed','rejected')", name=op.f('ck_account_mappings_status_valid')),
    sa.CheckConstraint('confidence >= 0 and confidence <= 1', name=op.f('ck_account_mappings_confidence_range')),
    sa.ForeignKeyConstraint(['decided_by'], ['users.id'], name=op.f('fk_account_mappings_decided_by_users')),
    sa.ForeignKeyConstraint(['entity_account_id'], ['entity_accounts.id'], name=op.f('fk_account_mappings_entity_account_id_entity_accounts'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['entity_id'], ['entities.id'], name=op.f('fk_account_mappings_entity_id_entities'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['group_account_id'], ['group_accounts.id'], name=op.f('fk_account_mappings_group_account_id_group_accounts'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_account_mappings_workspace_id_workspaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_account_mappings')),
    sa.UniqueConstraint('entity_account_id', name=op.f('uq_account_mappings_entity_account_id'))
    )
    op.create_index(op.f('ix_account_mappings_entity_id'), 'account_mappings', ['entity_id'], unique=False)
    op.create_index(op.f('ix_account_mappings_group_account_id'), 'account_mappings', ['group_account_id'], unique=False)
    op.create_index(op.f('ix_account_mappings_workspace_id'), 'account_mappings', ['workspace_id'], unique=False)
    # ### end Alembic commands ###

    # Row-level security, grants and privileged functions (see migrations/policies.py).
    op.execute(policies.UPGRADE)

    # Job queue schema. Sent through the raw psycopg connection: SQLAlchemy's
    # text() would treat parts of procrastinate's SQL as bind parameters.
    op.get_bind().connection.driver_connection.execute(SchemaManager.get_schema())
    op.execute(policies.procrastinate_grants())


def downgrade() -> None:
    op.execute("""
DO $$
DECLARE r record;
BEGIN
  -- Policies first: some reference other tables (e.g. memberships) or the context functions.
  FOR r IN SELECT policyname, tablename FROM pg_policies WHERE schemaname = 'public' LOOP
    EXECUTE format('DROP POLICY IF EXISTS %I ON public.%I', r.policyname, r.tablename);
  END LOOP;
  FOR r IN SELECT tablename FROM pg_tables WHERE schemaname = 'public' AND tablename LIKE 'procrastinate%' LOOP
    EXECUTE format('DROP TABLE IF EXISTS public.%I CASCADE', r.tablename);
  END LOOP;
  FOR r IN SELECT p.oid::regprocedure AS fn FROM pg_proc p JOIN pg_namespace n ON n.oid = p.pronamespace
            WHERE n.nspname = 'public' AND p.proname LIKE 'procrastinate%' LOOP
    EXECUTE format('DROP FUNCTION IF EXISTS %s CASCADE', r.fn);
  END LOOP;
  FOR r IN SELECT typname FROM pg_type t JOIN pg_namespace n ON n.oid = t.typnamespace
            WHERE n.nspname = 'public' AND t.typname LIKE 'procrastinate%'
              -- enums, and standalone composite types (not table row types)
              AND (t.typtype = 'e' OR (t.typtype = 'c' AND EXISTS (
                SELECT 1 FROM pg_class c WHERE c.oid = t.typrelid AND c.relkind = 'c'))) LOOP
    EXECUTE format('DROP TYPE IF EXISTS public.%I CASCADE', r.typname);
  END LOOP;
END $$;
""")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_account_mappings_workspace_id'), table_name='account_mappings')
    op.drop_index(op.f('ix_account_mappings_group_account_id'), table_name='account_mappings')
    op.drop_index(op.f('ix_account_mappings_entity_id'), table_name='account_mappings')
    op.drop_table('account_mappings')
    op.drop_index(op.f('ix_sync_runs_workspace_id'), table_name='sync_runs')
    op.drop_index(op.f('ix_sync_runs_entity_id'), table_name='sync_runs')
    op.drop_table('sync_runs')
    op.drop_index(op.f('ix_group_accounts_workspace_id'), table_name='group_accounts')
    op.drop_table('group_accounts')
    op.drop_index(op.f('ix_entity_accounts_workspace_id'), table_name='entity_accounts')
    op.drop_index(op.f('ix_entity_accounts_entity_id'), table_name='entity_accounts')
    op.drop_table('entity_accounts')
    op.drop_index(op.f('ix_entities_workspace_id'), table_name='entities')
    op.drop_index(op.f('ix_entities_connection_id'), table_name='entities')
    op.drop_table('entities')
    op.drop_index(op.f('ix_xero_connections_workspace_id'), table_name='xero_connections')
    op.drop_table('xero_connections')
    op.drop_index(op.f('ix_sessions_user_id'), table_name='sessions')
    op.drop_table('sessions')
    op.drop_index(op.f('ix_memberships_workspace_id'), table_name='memberships')
    op.drop_index(op.f('ix_memberships_user_id'), table_name='memberships')
    op.drop_table('memberships')
    op.drop_index(op.f('ix_invitations_workspace_id'), table_name='invitations')
    op.drop_table('invitations')
    op.drop_index(op.f('ix_audit_events_workspace_id'), table_name='audit_events')
    op.drop_table('audit_events')
    op.drop_table('workspaces')
    op.drop_table('xero_quota')
    op.drop_table('users')
    op.drop_table('oauth_states')
    # ### end Alembic commands ###
    # Functions last: the RLS policies on the tables above depend on them.
    op.execute(policies.DOWNGRADE)
    sa.Enum(name='role').drop(op.get_bind(), checkfirst=True)
